/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/_onboarding'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ApprovalRouteImport } from './routes/_approval'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiOgRouteImport } from './routes/api.og'
import { Route as OnboardingOnboardingRouteImport } from './routes/_onboarding/onboarding'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthAcceptInviteRouteImport } from './routes/_auth/accept-invite'
import { Route as ApprovalRejectedRouteImport } from './routes/_approval/rejected'
import { Route as ApprovalPendingApprovalRouteImport } from './routes/_approval/pending-approval'
import { Route as AppOrgSlugRouteImport } from './routes/_app/$orgSlug'
import { Route as AppOrgSlugIndexRouteImport } from './routes/_app/$orgSlug/index'
import { Route as AppOrgSlugWalletRouteImport } from './routes/_app/$orgSlug/wallet'
import { Route as AppOrgSlugTeamRouteImport } from './routes/_app/$orgSlug/team'
import { Route as AppOrgSlugSupportRouteImport } from './routes/_app/$orgSlug/support'
import { Route as AppOrgSlugSettingsRouteImport } from './routes/_app/$orgSlug/settings'
import { Route as AppOrgSlugListingsRouteImport } from './routes/_app/$orgSlug/listings'
import { Route as AppOrgSlugInvoicesRouteImport } from './routes/_app/$orgSlug/invoices'
import { Route as AppOrgSlugEnrollmentsRouteImport } from './routes/_app/$orgSlug/enrollments'
import { Route as AppOrgSlugCampaignsRouteImport } from './routes/_app/$orgSlug/campaigns'
import { Route as AppOrgSlugWalletIndexRouteImport } from './routes/_app/$orgSlug/wallet/index'
import { Route as AppOrgSlugTeamIndexRouteImport } from './routes/_app/$orgSlug/team/index'
import { Route as AppOrgSlugWalletWithdrawalsRouteImport } from './routes/_app/$orgSlug/wallet/withdrawals'
import { Route as AppOrgSlugWalletHoldsRouteImport } from './routes/_app/$orgSlug/wallet/holds'
import { Route as AppOrgSlugWalletDepositsRouteImport } from './routes/_app/$orgSlug/wallet/deposits'
import { Route as AppOrgSlugTeamRolesRouteImport } from './routes/_app/$orgSlug/team/roles'
import { Route as AppOrgSlugTeamInvitationsRouteImport } from './routes/_app/$orgSlug/team/invitations'
import { Route as AppOrgSlugSettingsAccountRouteImport } from './routes/_app/$orgSlug/settings_.account'
import { Route as AppOrgSlugListingsIdRouteImport } from './routes/_app/$orgSlug/listings_.$id'
import { Route as AppOrgSlugEnrollmentsIdRouteImport } from './routes/_app/$orgSlug/enrollments_.$id'
import { Route as AppOrgSlugCampaignsIdRouteImport } from './routes/_app/$orgSlug/campaigns_.$id'
import { Route as AppOrgSlugWalletTransactionsIdRouteImport } from './routes/_app/$orgSlug/wallet_.transactions_.$id'
import { Route as AppOrgSlugCampaignsCampaignIdEnrollmentsIdRouteImport } from './routes/_app/$orgSlug/campaigns_.$campaignId.enrollments_.$id'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/_onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalRoute = ApprovalRouteImport.update({
  id: '/_approval',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingOnboardingRoute = OnboardingOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => OnboardingRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAcceptInviteRoute = AuthAcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => AuthRoute,
} as any)
const ApprovalRejectedRoute = ApprovalRejectedRouteImport.update({
  id: '/rejected',
  path: '/rejected',
  getParentRoute: () => ApprovalRoute,
} as any)
const ApprovalPendingApprovalRoute = ApprovalPendingApprovalRouteImport.update({
  id: '/pending-approval',
  path: '/pending-approval',
  getParentRoute: () => ApprovalRoute,
} as any)
const AppOrgSlugRoute = AppOrgSlugRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgSlugIndexRoute = AppOrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrgSlugRoute,
} as any)
const AppOrgSlugWalletRoute = AppOrgSlugWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppOrgSlugRoute,
} as any)
const AppOrgSlugTeamRoute = AppOrgSlugTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppOrgSlugRoute,
} as any)
const AppOrgSlugSupportRoute = AppOrgSlugSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppOrgSlugRoute,
} as any)
const AppOrgSlugSettingsRoute = AppOrgSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppOrgSlugRoute,
} as any)
const AppOrgSlugListingsRoute = AppOrgSlugListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AppOrgSlugRoute,
} as any)
const AppOrgSlugInvoicesRoute = AppOrgSlugInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppOrgSlugRoute,
} as any)
const AppOrgSlugEnrollmentsRoute = AppOrgSlugEnrollmentsRouteImport.update({
  id: '/enrollments',
  path: '/enrollments',
  getParentRoute: () => AppOrgSlugRoute,
} as any)
const AppOrgSlugCampaignsRoute = AppOrgSlugCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppOrgSlugRoute,
} as any)
const AppOrgSlugWalletIndexRoute = AppOrgSlugWalletIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrgSlugWalletRoute,
} as any)
const AppOrgSlugTeamIndexRoute = AppOrgSlugTeamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrgSlugTeamRoute,
} as any)
const AppOrgSlugWalletWithdrawalsRoute =
  AppOrgSlugWalletWithdrawalsRouteImport.update({
    id: '/withdrawals',
    path: '/withdrawals',
    getParentRoute: () => AppOrgSlugWalletRoute,
  } as any)
const AppOrgSlugWalletHoldsRoute = AppOrgSlugWalletHoldsRouteImport.update({
  id: '/holds',
  path: '/holds',
  getParentRoute: () => AppOrgSlugWalletRoute,
} as any)
const AppOrgSlugWalletDepositsRoute =
  AppOrgSlugWalletDepositsRouteImport.update({
    id: '/deposits',
    path: '/deposits',
    getParentRoute: () => AppOrgSlugWalletRoute,
  } as any)
const AppOrgSlugTeamRolesRoute = AppOrgSlugTeamRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppOrgSlugTeamRoute,
} as any)
const AppOrgSlugTeamInvitationsRoute =
  AppOrgSlugTeamInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => AppOrgSlugTeamRoute,
  } as any)
const AppOrgSlugSettingsAccountRoute =
  AppOrgSlugSettingsAccountRouteImport.update({
    id: '/settings_/account',
    path: '/settings/account',
    getParentRoute: () => AppOrgSlugRoute,
  } as any)
const AppOrgSlugListingsIdRoute = AppOrgSlugListingsIdRouteImport.update({
  id: '/listings_/$id',
  path: '/listings/$id',
  getParentRoute: () => AppOrgSlugRoute,
} as any)
const AppOrgSlugEnrollmentsIdRoute = AppOrgSlugEnrollmentsIdRouteImport.update({
  id: '/enrollments_/$id',
  path: '/enrollments/$id',
  getParentRoute: () => AppOrgSlugRoute,
} as any)
const AppOrgSlugCampaignsIdRoute = AppOrgSlugCampaignsIdRouteImport.update({
  id: '/campaigns_/$id',
  path: '/campaigns/$id',
  getParentRoute: () => AppOrgSlugRoute,
} as any)
const AppOrgSlugWalletTransactionsIdRoute =
  AppOrgSlugWalletTransactionsIdRouteImport.update({
    id: '/wallet_/transactions_/$id',
    path: '/wallet/transactions/$id',
    getParentRoute: () => AppOrgSlugRoute,
  } as any)
const AppOrgSlugCampaignsCampaignIdEnrollmentsIdRoute =
  AppOrgSlugCampaignsCampaignIdEnrollmentsIdRouteImport.update({
    id: '/campaigns_/$campaignId/enrollments_/$id',
    path: '/campaigns/$campaignId/enrollments/$id',
    getParentRoute: () => AppOrgSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/$orgSlug': typeof AppOrgSlugRouteWithChildren
  '/pending-approval': typeof ApprovalPendingApprovalRoute
  '/rejected': typeof ApprovalRejectedRoute
  '/accept-invite': typeof AuthAcceptInviteRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/onboarding': typeof OnboardingOnboardingRoute
  '/api/og': typeof ApiOgRoute
  '/$orgSlug/campaigns': typeof AppOrgSlugCampaignsRoute
  '/$orgSlug/enrollments': typeof AppOrgSlugEnrollmentsRoute
  '/$orgSlug/invoices': typeof AppOrgSlugInvoicesRoute
  '/$orgSlug/listings': typeof AppOrgSlugListingsRoute
  '/$orgSlug/settings': typeof AppOrgSlugSettingsRoute
  '/$orgSlug/support': typeof AppOrgSlugSupportRoute
  '/$orgSlug/team': typeof AppOrgSlugTeamRouteWithChildren
  '/$orgSlug/wallet': typeof AppOrgSlugWalletRouteWithChildren
  '/$orgSlug/': typeof AppOrgSlugIndexRoute
  '/$orgSlug/campaigns/$id': typeof AppOrgSlugCampaignsIdRoute
  '/$orgSlug/enrollments/$id': typeof AppOrgSlugEnrollmentsIdRoute
  '/$orgSlug/listings/$id': typeof AppOrgSlugListingsIdRoute
  '/$orgSlug/settings/account': typeof AppOrgSlugSettingsAccountRoute
  '/$orgSlug/team/invitations': typeof AppOrgSlugTeamInvitationsRoute
  '/$orgSlug/team/roles': typeof AppOrgSlugTeamRolesRoute
  '/$orgSlug/wallet/deposits': typeof AppOrgSlugWalletDepositsRoute
  '/$orgSlug/wallet/holds': typeof AppOrgSlugWalletHoldsRoute
  '/$orgSlug/wallet/withdrawals': typeof AppOrgSlugWalletWithdrawalsRoute
  '/$orgSlug/team/': typeof AppOrgSlugTeamIndexRoute
  '/$orgSlug/wallet/': typeof AppOrgSlugWalletIndexRoute
  '/$orgSlug/wallet/transactions/$id': typeof AppOrgSlugWalletTransactionsIdRoute
  '/$orgSlug/campaigns/$campaignId/enrollments/$id': typeof AppOrgSlugCampaignsCampaignIdEnrollmentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/pending-approval': typeof ApprovalPendingApprovalRoute
  '/rejected': typeof ApprovalRejectedRoute
  '/accept-invite': typeof AuthAcceptInviteRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/onboarding': typeof OnboardingOnboardingRoute
  '/api/og': typeof ApiOgRoute
  '/$orgSlug/campaigns': typeof AppOrgSlugCampaignsRoute
  '/$orgSlug/enrollments': typeof AppOrgSlugEnrollmentsRoute
  '/$orgSlug/invoices': typeof AppOrgSlugInvoicesRoute
  '/$orgSlug/listings': typeof AppOrgSlugListingsRoute
  '/$orgSlug/settings': typeof AppOrgSlugSettingsRoute
  '/$orgSlug/support': typeof AppOrgSlugSupportRoute
  '/$orgSlug': typeof AppOrgSlugIndexRoute
  '/$orgSlug/campaigns/$id': typeof AppOrgSlugCampaignsIdRoute
  '/$orgSlug/enrollments/$id': typeof AppOrgSlugEnrollmentsIdRoute
  '/$orgSlug/listings/$id': typeof AppOrgSlugListingsIdRoute
  '/$orgSlug/settings/account': typeof AppOrgSlugSettingsAccountRoute
  '/$orgSlug/team/invitations': typeof AppOrgSlugTeamInvitationsRoute
  '/$orgSlug/team/roles': typeof AppOrgSlugTeamRolesRoute
  '/$orgSlug/wallet/deposits': typeof AppOrgSlugWalletDepositsRoute
  '/$orgSlug/wallet/holds': typeof AppOrgSlugWalletHoldsRoute
  '/$orgSlug/wallet/withdrawals': typeof AppOrgSlugWalletWithdrawalsRoute
  '/$orgSlug/team': typeof AppOrgSlugTeamIndexRoute
  '/$orgSlug/wallet': typeof AppOrgSlugWalletIndexRoute
  '/$orgSlug/wallet/transactions/$id': typeof AppOrgSlugWalletTransactionsIdRoute
  '/$orgSlug/campaigns/$campaignId/enrollments/$id': typeof AppOrgSlugCampaignsCampaignIdEnrollmentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_approval': typeof ApprovalRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_onboarding': typeof OnboardingRouteWithChildren
  '/_app/$orgSlug': typeof AppOrgSlugRouteWithChildren
  '/_approval/pending-approval': typeof ApprovalPendingApprovalRoute
  '/_approval/rejected': typeof ApprovalRejectedRoute
  '/_auth/accept-invite': typeof AuthAcceptInviteRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_onboarding/onboarding': typeof OnboardingOnboardingRoute
  '/api/og': typeof ApiOgRoute
  '/_app/': typeof AppIndexRoute
  '/_app/$orgSlug/campaigns': typeof AppOrgSlugCampaignsRoute
  '/_app/$orgSlug/enrollments': typeof AppOrgSlugEnrollmentsRoute
  '/_app/$orgSlug/invoices': typeof AppOrgSlugInvoicesRoute
  '/_app/$orgSlug/listings': typeof AppOrgSlugListingsRoute
  '/_app/$orgSlug/settings': typeof AppOrgSlugSettingsRoute
  '/_app/$orgSlug/support': typeof AppOrgSlugSupportRoute
  '/_app/$orgSlug/team': typeof AppOrgSlugTeamRouteWithChildren
  '/_app/$orgSlug/wallet': typeof AppOrgSlugWalletRouteWithChildren
  '/_app/$orgSlug/': typeof AppOrgSlugIndexRoute
  '/_app/$orgSlug/campaigns_/$id': typeof AppOrgSlugCampaignsIdRoute
  '/_app/$orgSlug/enrollments_/$id': typeof AppOrgSlugEnrollmentsIdRoute
  '/_app/$orgSlug/listings_/$id': typeof AppOrgSlugListingsIdRoute
  '/_app/$orgSlug/settings_/account': typeof AppOrgSlugSettingsAccountRoute
  '/_app/$orgSlug/team/invitations': typeof AppOrgSlugTeamInvitationsRoute
  '/_app/$orgSlug/team/roles': typeof AppOrgSlugTeamRolesRoute
  '/_app/$orgSlug/wallet/deposits': typeof AppOrgSlugWalletDepositsRoute
  '/_app/$orgSlug/wallet/holds': typeof AppOrgSlugWalletHoldsRoute
  '/_app/$orgSlug/wallet/withdrawals': typeof AppOrgSlugWalletWithdrawalsRoute
  '/_app/$orgSlug/team/': typeof AppOrgSlugTeamIndexRoute
  '/_app/$orgSlug/wallet/': typeof AppOrgSlugWalletIndexRoute
  '/_app/$orgSlug/wallet_/transactions_/$id': typeof AppOrgSlugWalletTransactionsIdRoute
  '/_app/$orgSlug/campaigns_/$campaignId/enrollments_/$id': typeof AppOrgSlugCampaignsCampaignIdEnrollmentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$orgSlug'
    | '/pending-approval'
    | '/rejected'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/onboarding'
    | '/api/og'
    | '/$orgSlug/campaigns'
    | '/$orgSlug/enrollments'
    | '/$orgSlug/invoices'
    | '/$orgSlug/listings'
    | '/$orgSlug/settings'
    | '/$orgSlug/support'
    | '/$orgSlug/team'
    | '/$orgSlug/wallet'
    | '/$orgSlug/'
    | '/$orgSlug/campaigns/$id'
    | '/$orgSlug/enrollments/$id'
    | '/$orgSlug/listings/$id'
    | '/$orgSlug/settings/account'
    | '/$orgSlug/team/invitations'
    | '/$orgSlug/team/roles'
    | '/$orgSlug/wallet/deposits'
    | '/$orgSlug/wallet/holds'
    | '/$orgSlug/wallet/withdrawals'
    | '/$orgSlug/team/'
    | '/$orgSlug/wallet/'
    | '/$orgSlug/wallet/transactions/$id'
    | '/$orgSlug/campaigns/$campaignId/enrollments/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pending-approval'
    | '/rejected'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/onboarding'
    | '/api/og'
    | '/$orgSlug/campaigns'
    | '/$orgSlug/enrollments'
    | '/$orgSlug/invoices'
    | '/$orgSlug/listings'
    | '/$orgSlug/settings'
    | '/$orgSlug/support'
    | '/$orgSlug'
    | '/$orgSlug/campaigns/$id'
    | '/$orgSlug/enrollments/$id'
    | '/$orgSlug/listings/$id'
    | '/$orgSlug/settings/account'
    | '/$orgSlug/team/invitations'
    | '/$orgSlug/team/roles'
    | '/$orgSlug/wallet/deposits'
    | '/$orgSlug/wallet/holds'
    | '/$orgSlug/wallet/withdrawals'
    | '/$orgSlug/team'
    | '/$orgSlug/wallet'
    | '/$orgSlug/wallet/transactions/$id'
    | '/$orgSlug/campaigns/$campaignId/enrollments/$id'
  id:
    | '__root__'
    | '/_app'
    | '/_approval'
    | '/_auth'
    | '/_onboarding'
    | '/_app/$orgSlug'
    | '/_approval/pending-approval'
    | '/_approval/rejected'
    | '/_auth/accept-invite'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_auth/verify-email'
    | '/_onboarding/onboarding'
    | '/api/og'
    | '/_app/'
    | '/_app/$orgSlug/campaigns'
    | '/_app/$orgSlug/enrollments'
    | '/_app/$orgSlug/invoices'
    | '/_app/$orgSlug/listings'
    | '/_app/$orgSlug/settings'
    | '/_app/$orgSlug/support'
    | '/_app/$orgSlug/team'
    | '/_app/$orgSlug/wallet'
    | '/_app/$orgSlug/'
    | '/_app/$orgSlug/campaigns_/$id'
    | '/_app/$orgSlug/enrollments_/$id'
    | '/_app/$orgSlug/listings_/$id'
    | '/_app/$orgSlug/settings_/account'
    | '/_app/$orgSlug/team/invitations'
    | '/_app/$orgSlug/team/roles'
    | '/_app/$orgSlug/wallet/deposits'
    | '/_app/$orgSlug/wallet/holds'
    | '/_app/$orgSlug/wallet/withdrawals'
    | '/_app/$orgSlug/team/'
    | '/_app/$orgSlug/wallet/'
    | '/_app/$orgSlug/wallet_/transactions_/$id'
    | '/_app/$orgSlug/campaigns_/$campaignId/enrollments_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ApprovalRoute: typeof ApprovalRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
  ApiOgRoute: typeof ApiOgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_onboarding': {
      id: '/_onboarding'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_approval': {
      id: '/_approval'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_onboarding/onboarding': {
      id: '/_onboarding/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingOnboardingRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/accept-invite': {
      id: '/_auth/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AuthAcceptInviteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_approval/rejected': {
      id: '/_approval/rejected'
      path: '/rejected'
      fullPath: '/rejected'
      preLoaderRoute: typeof ApprovalRejectedRouteImport
      parentRoute: typeof ApprovalRoute
    }
    '/_approval/pending-approval': {
      id: '/_approval/pending-approval'
      path: '/pending-approval'
      fullPath: '/pending-approval'
      preLoaderRoute: typeof ApprovalPendingApprovalRouteImport
      parentRoute: typeof ApprovalRoute
    }
    '/_app/$orgSlug': {
      id: '/_app/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof AppOrgSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$orgSlug/': {
      id: '/_app/$orgSlug/'
      path: '/'
      fullPath: '/$orgSlug/'
      preLoaderRoute: typeof AppOrgSlugIndexRouteImport
      parentRoute: typeof AppOrgSlugRoute
    }
    '/_app/$orgSlug/wallet': {
      id: '/_app/$orgSlug/wallet'
      path: '/wallet'
      fullPath: '/$orgSlug/wallet'
      preLoaderRoute: typeof AppOrgSlugWalletRouteImport
      parentRoute: typeof AppOrgSlugRoute
    }
    '/_app/$orgSlug/team': {
      id: '/_app/$orgSlug/team'
      path: '/team'
      fullPath: '/$orgSlug/team'
      preLoaderRoute: typeof AppOrgSlugTeamRouteImport
      parentRoute: typeof AppOrgSlugRoute
    }
    '/_app/$orgSlug/support': {
      id: '/_app/$orgSlug/support'
      path: '/support'
      fullPath: '/$orgSlug/support'
      preLoaderRoute: typeof AppOrgSlugSupportRouteImport
      parentRoute: typeof AppOrgSlugRoute
    }
    '/_app/$orgSlug/settings': {
      id: '/_app/$orgSlug/settings'
      path: '/settings'
      fullPath: '/$orgSlug/settings'
      preLoaderRoute: typeof AppOrgSlugSettingsRouteImport
      parentRoute: typeof AppOrgSlugRoute
    }
    '/_app/$orgSlug/listings': {
      id: '/_app/$orgSlug/listings'
      path: '/listings'
      fullPath: '/$orgSlug/listings'
      preLoaderRoute: typeof AppOrgSlugListingsRouteImport
      parentRoute: typeof AppOrgSlugRoute
    }
    '/_app/$orgSlug/invoices': {
      id: '/_app/$orgSlug/invoices'
      path: '/invoices'
      fullPath: '/$orgSlug/invoices'
      preLoaderRoute: typeof AppOrgSlugInvoicesRouteImport
      parentRoute: typeof AppOrgSlugRoute
    }
    '/_app/$orgSlug/enrollments': {
      id: '/_app/$orgSlug/enrollments'
      path: '/enrollments'
      fullPath: '/$orgSlug/enrollments'
      preLoaderRoute: typeof AppOrgSlugEnrollmentsRouteImport
      parentRoute: typeof AppOrgSlugRoute
    }
    '/_app/$orgSlug/campaigns': {
      id: '/_app/$orgSlug/campaigns'
      path: '/campaigns'
      fullPath: '/$orgSlug/campaigns'
      preLoaderRoute: typeof AppOrgSlugCampaignsRouteImport
      parentRoute: typeof AppOrgSlugRoute
    }
    '/_app/$orgSlug/wallet/': {
      id: '/_app/$orgSlug/wallet/'
      path: '/'
      fullPath: '/$orgSlug/wallet/'
      preLoaderRoute: typeof AppOrgSlugWalletIndexRouteImport
      parentRoute: typeof AppOrgSlugWalletRoute
    }
    '/_app/$orgSlug/team/': {
      id: '/_app/$orgSlug/team/'
      path: '/'
      fullPath: '/$orgSlug/team/'
      preLoaderRoute: typeof AppOrgSlugTeamIndexRouteImport
      parentRoute: typeof AppOrgSlugTeamRoute
    }
    '/_app/$orgSlug/wallet/withdrawals': {
      id: '/_app/$orgSlug/wallet/withdrawals'
      path: '/withdrawals'
      fullPath: '/$orgSlug/wallet/withdrawals'
      preLoaderRoute: typeof AppOrgSlugWalletWithdrawalsRouteImport
      parentRoute: typeof AppOrgSlugWalletRoute
    }
    '/_app/$orgSlug/wallet/holds': {
      id: '/_app/$orgSlug/wallet/holds'
      path: '/holds'
      fullPath: '/$orgSlug/wallet/holds'
      preLoaderRoute: typeof AppOrgSlugWalletHoldsRouteImport
      parentRoute: typeof AppOrgSlugWalletRoute
    }
    '/_app/$orgSlug/wallet/deposits': {
      id: '/_app/$orgSlug/wallet/deposits'
      path: '/deposits'
      fullPath: '/$orgSlug/wallet/deposits'
      preLoaderRoute: typeof AppOrgSlugWalletDepositsRouteImport
      parentRoute: typeof AppOrgSlugWalletRoute
    }
    '/_app/$orgSlug/team/roles': {
      id: '/_app/$orgSlug/team/roles'
      path: '/roles'
      fullPath: '/$orgSlug/team/roles'
      preLoaderRoute: typeof AppOrgSlugTeamRolesRouteImport
      parentRoute: typeof AppOrgSlugTeamRoute
    }
    '/_app/$orgSlug/team/invitations': {
      id: '/_app/$orgSlug/team/invitations'
      path: '/invitations'
      fullPath: '/$orgSlug/team/invitations'
      preLoaderRoute: typeof AppOrgSlugTeamInvitationsRouteImport
      parentRoute: typeof AppOrgSlugTeamRoute
    }
    '/_app/$orgSlug/settings_/account': {
      id: '/_app/$orgSlug/settings_/account'
      path: '/settings/account'
      fullPath: '/$orgSlug/settings/account'
      preLoaderRoute: typeof AppOrgSlugSettingsAccountRouteImport
      parentRoute: typeof AppOrgSlugRoute
    }
    '/_app/$orgSlug/listings_/$id': {
      id: '/_app/$orgSlug/listings_/$id'
      path: '/listings/$id'
      fullPath: '/$orgSlug/listings/$id'
      preLoaderRoute: typeof AppOrgSlugListingsIdRouteImport
      parentRoute: typeof AppOrgSlugRoute
    }
    '/_app/$orgSlug/enrollments_/$id': {
      id: '/_app/$orgSlug/enrollments_/$id'
      path: '/enrollments/$id'
      fullPath: '/$orgSlug/enrollments/$id'
      preLoaderRoute: typeof AppOrgSlugEnrollmentsIdRouteImport
      parentRoute: typeof AppOrgSlugRoute
    }
    '/_app/$orgSlug/campaigns_/$id': {
      id: '/_app/$orgSlug/campaigns_/$id'
      path: '/campaigns/$id'
      fullPath: '/$orgSlug/campaigns/$id'
      preLoaderRoute: typeof AppOrgSlugCampaignsIdRouteImport
      parentRoute: typeof AppOrgSlugRoute
    }
    '/_app/$orgSlug/wallet_/transactions_/$id': {
      id: '/_app/$orgSlug/wallet_/transactions_/$id'
      path: '/wallet/transactions/$id'
      fullPath: '/$orgSlug/wallet/transactions/$id'
      preLoaderRoute: typeof AppOrgSlugWalletTransactionsIdRouteImport
      parentRoute: typeof AppOrgSlugRoute
    }
    '/_app/$orgSlug/campaigns_/$campaignId/enrollments_/$id': {
      id: '/_app/$orgSlug/campaigns_/$campaignId/enrollments_/$id'
      path: '/campaigns/$campaignId/enrollments/$id'
      fullPath: '/$orgSlug/campaigns/$campaignId/enrollments/$id'
      preLoaderRoute: typeof AppOrgSlugCampaignsCampaignIdEnrollmentsIdRouteImport
      parentRoute: typeof AppOrgSlugRoute
    }
  }
}

interface AppOrgSlugTeamRouteChildren {
  AppOrgSlugTeamInvitationsRoute: typeof AppOrgSlugTeamInvitationsRoute
  AppOrgSlugTeamRolesRoute: typeof AppOrgSlugTeamRolesRoute
  AppOrgSlugTeamIndexRoute: typeof AppOrgSlugTeamIndexRoute
}

const AppOrgSlugTeamRouteChildren: AppOrgSlugTeamRouteChildren = {
  AppOrgSlugTeamInvitationsRoute: AppOrgSlugTeamInvitationsRoute,
  AppOrgSlugTeamRolesRoute: AppOrgSlugTeamRolesRoute,
  AppOrgSlugTeamIndexRoute: AppOrgSlugTeamIndexRoute,
}

const AppOrgSlugTeamRouteWithChildren = AppOrgSlugTeamRoute._addFileChildren(
  AppOrgSlugTeamRouteChildren,
)

interface AppOrgSlugWalletRouteChildren {
  AppOrgSlugWalletDepositsRoute: typeof AppOrgSlugWalletDepositsRoute
  AppOrgSlugWalletHoldsRoute: typeof AppOrgSlugWalletHoldsRoute
  AppOrgSlugWalletWithdrawalsRoute: typeof AppOrgSlugWalletWithdrawalsRoute
  AppOrgSlugWalletIndexRoute: typeof AppOrgSlugWalletIndexRoute
}

const AppOrgSlugWalletRouteChildren: AppOrgSlugWalletRouteChildren = {
  AppOrgSlugWalletDepositsRoute: AppOrgSlugWalletDepositsRoute,
  AppOrgSlugWalletHoldsRoute: AppOrgSlugWalletHoldsRoute,
  AppOrgSlugWalletWithdrawalsRoute: AppOrgSlugWalletWithdrawalsRoute,
  AppOrgSlugWalletIndexRoute: AppOrgSlugWalletIndexRoute,
}

const AppOrgSlugWalletRouteWithChildren =
  AppOrgSlugWalletRoute._addFileChildren(AppOrgSlugWalletRouteChildren)

interface AppOrgSlugRouteChildren {
  AppOrgSlugCampaignsRoute: typeof AppOrgSlugCampaignsRoute
  AppOrgSlugEnrollmentsRoute: typeof AppOrgSlugEnrollmentsRoute
  AppOrgSlugInvoicesRoute: typeof AppOrgSlugInvoicesRoute
  AppOrgSlugListingsRoute: typeof AppOrgSlugListingsRoute
  AppOrgSlugSettingsRoute: typeof AppOrgSlugSettingsRoute
  AppOrgSlugSupportRoute: typeof AppOrgSlugSupportRoute
  AppOrgSlugTeamRoute: typeof AppOrgSlugTeamRouteWithChildren
  AppOrgSlugWalletRoute: typeof AppOrgSlugWalletRouteWithChildren
  AppOrgSlugIndexRoute: typeof AppOrgSlugIndexRoute
  AppOrgSlugCampaignsIdRoute: typeof AppOrgSlugCampaignsIdRoute
  AppOrgSlugEnrollmentsIdRoute: typeof AppOrgSlugEnrollmentsIdRoute
  AppOrgSlugListingsIdRoute: typeof AppOrgSlugListingsIdRoute
  AppOrgSlugSettingsAccountRoute: typeof AppOrgSlugSettingsAccountRoute
  AppOrgSlugWalletTransactionsIdRoute: typeof AppOrgSlugWalletTransactionsIdRoute
  AppOrgSlugCampaignsCampaignIdEnrollmentsIdRoute: typeof AppOrgSlugCampaignsCampaignIdEnrollmentsIdRoute
}

const AppOrgSlugRouteChildren: AppOrgSlugRouteChildren = {
  AppOrgSlugCampaignsRoute: AppOrgSlugCampaignsRoute,
  AppOrgSlugEnrollmentsRoute: AppOrgSlugEnrollmentsRoute,
  AppOrgSlugInvoicesRoute: AppOrgSlugInvoicesRoute,
  AppOrgSlugListingsRoute: AppOrgSlugListingsRoute,
  AppOrgSlugSettingsRoute: AppOrgSlugSettingsRoute,
  AppOrgSlugSupportRoute: AppOrgSlugSupportRoute,
  AppOrgSlugTeamRoute: AppOrgSlugTeamRouteWithChildren,
  AppOrgSlugWalletRoute: AppOrgSlugWalletRouteWithChildren,
  AppOrgSlugIndexRoute: AppOrgSlugIndexRoute,
  AppOrgSlugCampaignsIdRoute: AppOrgSlugCampaignsIdRoute,
  AppOrgSlugEnrollmentsIdRoute: AppOrgSlugEnrollmentsIdRoute,
  AppOrgSlugListingsIdRoute: AppOrgSlugListingsIdRoute,
  AppOrgSlugSettingsAccountRoute: AppOrgSlugSettingsAccountRoute,
  AppOrgSlugWalletTransactionsIdRoute: AppOrgSlugWalletTransactionsIdRoute,
  AppOrgSlugCampaignsCampaignIdEnrollmentsIdRoute:
    AppOrgSlugCampaignsCampaignIdEnrollmentsIdRoute,
}

const AppOrgSlugRouteWithChildren = AppOrgSlugRoute._addFileChildren(
  AppOrgSlugRouteChildren,
)

interface AppRouteChildren {
  AppOrgSlugRoute: typeof AppOrgSlugRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppOrgSlugRoute: AppOrgSlugRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApprovalRouteChildren {
  ApprovalPendingApprovalRoute: typeof ApprovalPendingApprovalRoute
  ApprovalRejectedRoute: typeof ApprovalRejectedRoute
}

const ApprovalRouteChildren: ApprovalRouteChildren = {
  ApprovalPendingApprovalRoute: ApprovalPendingApprovalRoute,
  ApprovalRejectedRoute: ApprovalRejectedRoute,
}

const ApprovalRouteWithChildren = ApprovalRoute._addFileChildren(
  ApprovalRouteChildren,
)

interface AuthRouteChildren {
  AuthAcceptInviteRoute: typeof AuthAcceptInviteRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAcceptInviteRoute: AuthAcceptInviteRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface OnboardingRouteChildren {
  OnboardingOnboardingRoute: typeof OnboardingOnboardingRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingOnboardingRoute: OnboardingOnboardingRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ApprovalRoute: ApprovalRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
  ApiOgRoute: ApiOgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
